### ISSUE TITLE
Invalide scope : relationships.read

### ISSUE THREAD

**Issue by QuentinSc** [luizkc/firebase-discord-oauth2-example#7]
Hello and thank you for your work.

Got an issue and can't find why.
If I add "relationships.read" in  oauthKeys.scopes I got the following error 

`AuthorizationError: The requested scope is invalid, unknown, or malformed. at Strategy.OAuth2Strategy.authenticate (/workspace/node_modules/passport-oauth2/lib/strategy.js:137:25) at attempt (/workspace/node_modules/passport/lib/middleware/authenticate.js:366:16) at authenticate (/workspace/node_modules/passport/lib/middleware/authenticate.js:367:7) at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5) at next (/workspace/node_modules/express/lib/router/route.js:137:13) at Route.dispatch (/workspace/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)`

No problem if my scope is only ["identify", "email", "guilds"]

relationships.read is not a supported scope ?

Thank you!

**Comment by QuentinSc** [comment]
My bas, need to be whitelisted by discord
